### ISSUE TITLE
是否可以设置不展示LD热图

### ISSUE THREAD

**Issue by zhoudreames** [hewm2008/LDBlockShow#1]
由于我区间的点的数量太多了 我只想展示除热图外的其他部分，该怎么设置呢？
![image](https://github.com/hewm2008/LDBlockShow/assets/54714639/dfcbef02-9944-4458-8b18-8211fc16ddef)

**Comment by hewm2008** [comment]
可以的 ，这儿有参数的，即   -NoHeatMapPlot   不画下面的LDheatmap        .    -NoShow 只计算不画图
