### ISSUE TITLE
UnKnow argument -crMiddle

### ISSUE THREAD

**Issue by xu199812** [hewm2008/LDBlockShow#4]
I want to change the color of the heatmap according to the operation document, but it prompts UnKnow argument -crMiddle.

**Comment by xu199812** [comment]
This is my complete order
LDBlockShow -InVCF out_4.vcf.gz -OutPut outYSM -Region 10:1-23420 -crMiddle 192,192,192 -crEnd 64,64,64 -OutPng -SeleVar 2

**Comment by hewm2008** [comment]
Re-plot Fig  by   ShowLDSVG   After  LDBlockShow 
like  thie : 
ShowLDSVG -InPreFix file -OutPut fileout -crMiddle 192,192,192 -crEnd 64,64,64 -crTagSNP 255,0,0 -OutPdf
see  more 
https://www.cnblogs.com/chenwenyan/p/13526771.html

**Comment by xu199812** [comment]
thanks！
